import { Book } from './types';
import { Timestamp } from 'firebase/firestore';

export const mockBooks: Omit<Book, 'id'>[] = [
  {
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    description: 'A shocking psychological thriller of a woman\'s act of violence against her husband—and of the therapist obsessed with uncovering her motive.',
    category: 'Thriller',
    condition: 'new',
    price: 1500,
    currency: 'PKR',
    stock: 10,
    images: ['https://picsum.photos/seed/book1/600/800'],
    sellerId: 'seller_1',
    sellerName: 'Bookworm Haven',
    city: 'Karachi',
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
    rating: 4.5,
    reviewsCount: 120,
  },
  {
    title: 'Atomic Habits',
    author: 'James Clear',
    description: 'An easy and proven way to build good habits and break bad ones. A revolutionary system to get 1 percent better every day.',
    category: 'Self-Help',
    condition: 'used',
    price: 800,
    currency: 'PKR',
    stock: 5,
    images: ['https://picsum.photos/seed/book2/600/800'],
    sellerId: 'seller_2',
    sellerName: 'PageTurners',
    city: 'Lahore',
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
    rating: 4.8,
    reviewsCount: 250,
  },
  {
    title: 'Where the Crawdads Sing',
    author: 'Delia Owens',
    description: 'A heartbreaking coming-of-age story and a surprising tale of possible murder. Owens reminds us that we are forever shaped by the children we once were.',
    category: 'Fiction',
    condition: 'new',
    price: 1200,
    currency: 'PKR',
    stock: 15,
    images: ['https://picsum.photos/seed/book3/600/800'],
    sellerId: 'seller_1',
    sellerName: 'Bookworm Haven',
    city: 'Karachi',
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
    rating: 4.7,
    reviewsCount: 180,
  },
  {
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    description: 'A groundbreaking narrative of humanity\'s creation and evolution that explores the ways in which biology and history have defined us.',
    category: 'History',
    condition: 'new',
    price: 2000,
    currency: 'PKR',
    stock: 8,
    images: ['https://picsum.photos/seed/book4/600/800'],
    sellerId: 'seller_3',
    sellerName: 'Lahore Reads',
    city: 'Lahore',
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
    rating: 4.6,
    reviewsCount: 300,
  },
  {
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    description: 'A classic novel of the Jazz Age, about the mysterious millionaire Jay Gatsby and his obsession for the beautiful Daisy Buchanan.',
    category: 'Classic',
    condition: 'used',
    price: 600,
    currency: 'PKR',
    stock: 20,
    images: ['https://picsum.photos/seed/book5/600/800'],
    sellerId: 'seller_2',
    sellerName: 'PageTurners',
    city: 'Lahore',
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
    rating: 4.4,
    reviewsCount: 500,
  },
  {
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    description: 'A lone astronaut must save the earth from disaster in this incredible new science-based thriller from the author of The Martian.',
    category: 'Sci-Fi',
    condition: 'new',
    price: 1800,
    currency: 'PKR',
    stock: 12,
    images: ['https://picsum.photos/seed/book6/600/800'],
    sellerId: 'seller_3',
    sellerName: 'Lahore Reads',
    city: 'Islamabad',
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
    rating: 4.9,
    reviewsCount: 95,
  },
  {
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    description: 'Timeless lessons on wealth, greed, and happiness. Doing well with money isn’t necessarily about what you know. It’s about how you behave.',
    category: 'Finance',
    condition: 'used',
    price: 950,
    currency: 'PKR',
    stock: 7,
    images: ['https://picsum.photos/seed/book7/600/800'],
    sellerId: 'seller_1',
    sellerName: 'Bookworm Haven',
    city: 'Karachi',
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
    rating: 4.7,
    reviewsCount: 150,
  },
  {
    title: 'Educated: A Memoir',
    author: 'Tara Westover',
    description: 'An unforgettable memoir about a young girl who, kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University.',
    category: 'Biography',
    condition: 'new',
    price: 1300,
    currency: 'PKR',
    stock: 11,
    images: ['https://picsum.photos/seed/book8/600/800'],
    sellerId: 'seller_4',
    sellerName: 'Indus Books',
    city: 'Peshawar',
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
    rating: 4.8,
    reviewsCount: 220,
  },
];
